### ISSUE TITLE
로그인 프로세스 에러

### ISSUE THREAD

**Issue by woong7361** [cpk0709/hanghae_9team_week1#13]
Merge후 SignUp으로 회원가입 후 SignIn으로 로그인 시도 시 에러가 일어납니다.

TypeError
TypeError: 'NoneType' object is not subscriptable

Traceback (most recent call last)
File "/home/woong/code/sparata/project/bucket/venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)

File "/home/woong/code/sparata/project/bucket/venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)

File "/home/woong/code/sparata/project/bucket/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()

File "/home/woong/code/sparata/project/bucket/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)

File "/home/woong/code/sparata/project/bucket/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()

File "/home/woong/code/sparata/project/bucket/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

File "/home/woong/code/sparata/hanghae_9team_week1/app.py", line 61, in signInJwt
msg = signInProcess(id, pw)

File "/home/woong/code/sparata/hanghae_9team_week1/python/user/signIn.py", line 22, in signInProcess
_id = str(result['_id'])

TypeError: 'NoneType' object is not subscriptable

**Comment by catalinakim** [comment]
로그인 수정 완료하였습니다.
